package com.grp12.softskilltools.SOAP;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/10/2017 5:57:43 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.ServermanagerService.Vectorbelbin;
import com.Wsdl2Code.WebServices.ServermanagerService.Vectordisc;
import com.Wsdl2Code.WebServices.ServermanagerService.Vectorthreesixty;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class safe implements KvmSerializable {
    
    public Vectorbelbin unusedBelbinItems;
    public Vectordisc unusedDiscItems;
    public Vectorthreesixty unusedThreeSixtyItems;
    public Vectorbelbin usedBelbinItems;
    public Vectordisc usedDiscItems;
    public Vectorthreesixty usedThreeSixtyItems;
    
    public safe(){}
    
    public safe(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("unusedBelbinItems"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("unusedBelbinItems");
            unusedBelbinItems = new Vectorbelbin(j);
        }
        if (soapObject.hasProperty("unusedDiscItems"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("unusedDiscItems");
            unusedDiscItems = new Vectordisc(j);
        }
        if (soapObject.hasProperty("unusedThreeSixtyItems"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("unusedThreeSixtyItems");
            unusedThreeSixtyItems = new Vectorthreesixty(j);
        }
        if (soapObject.hasProperty("usedBelbinItems"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("usedBelbinItems");
            usedBelbinItems = new Vectorbelbin(j);
        }
        if (soapObject.hasProperty("usedDiscItems"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("usedDiscItems");
            usedDiscItems = new Vectordisc(j);
        }
        if (soapObject.hasProperty("usedThreeSixtyItems"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("usedThreeSixtyItems");
            usedThreeSixtyItems = new Vectorthreesixty(j);
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return unusedBelbinItems;
            case 1:
                return unusedDiscItems;
            case 2:
                return unusedThreeSixtyItems;
            case 3:
                return usedBelbinItems;
            case 4:
                return usedDiscItems;
            case 5:
                return usedThreeSixtyItems;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 6;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "unusedBelbinItems";
                break;
            case 1:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "unusedDiscItems";
                break;
            case 2:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "unusedThreeSixtyItems";
                break;
            case 3:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "usedBelbinItems";
                break;
            case 4:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "usedDiscItems";
                break;
            case 5:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "usedThreeSixtyItems";
                break;
        }
    }
    
    @Override
    public String getInnerText() {
        return null;
    }
    
    
    @Override
    public void setInnerText(String s) {
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
