package com.grp12.softskilltools.SOAP;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/13/2017 3:12:55 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
public class WS_Enums {

    public enum SoapProtocolVersion{
        	Default(0),
        	Soap11(1),
        	Soap12(2);
        
        private int code;
        
        SoapProtocolVersion(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static SoapProtocolVersion fromString(String str)
        {
            if (str.equals("Default"))
                return Default;
            if (str.equals("Soap11"))
                return Soap11;
            if (str.equals("Soap12"))
                return Soap12;
            return null;
        }
    }
    public enum testType{
        	DISC(0),
        	BELBIN(1),
        	THREESIXTY(2);
        
        private int code;
        
        testType(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static testType fromString(String str)
        {
            if (str.equals("DISC"))
                return DISC;
            if (str.equals("BELBIN"))
                return BELBIN;
            if (str.equals("THREESIXTY"))
                return THREESIXTY;
            return null;
        }
    }
    public enum questionType{
        	Dom(0),
        	Inf(1),
        	Sta(2),
        	Com(3),
        	PL(4),
        	RI(5),
        	CO(6),
        	SH(7),
        	ME(8),
        	TW(9),
        	IMP(10),
        	CF(11),
        	SP(12),
        	DROP(13);
        
        private int code;
        
        questionType(int code){
            this.code = code;
        }
        
        public int getCode(){
            return code;
        }
        
        public static questionType fromString(String str)
        {
            if (str.equals("Dom"))
                return Dom;
            if (str.equals("Inf"))
                return Inf;
            if (str.equals("Sta"))
                return Sta;
            if (str.equals("Com"))
                return Com;
            if (str.equals("PL"))
                return PL;
            if (str.equals("RI"))
                return RI;
            if (str.equals("CO"))
                return CO;
            if (str.equals("SH"))
                return SH;
            if (str.equals("ME"))
                return ME;
            if (str.equals("TW"))
                return TW;
            if (str.equals("IMP"))
                return IMP;
            if (str.equals("CF"))
                return CF;
            if (str.equals("SP"))
                return SP;
            if (str.equals("DROP"))
                return DROP;
            return null;
        }
    }
}
